//
// Plugin:        smplugin_src.js
//
// Description:   This plugin allows for displaying a dialogue for inserting
//                code into a post, page, etc.
//
// Copyrighted by Custom Computer Tools and Richard Guay
// Build February 27, 2012
//
(function(){tinymce.create('tinymce.plugins.smplugin',{init:function(ed,url){ed.addCommand('insertCode',function(){cmd='';cctSMprog.ed=ed;var begin="Script Language: <select name='scriptlang' id='scriptlang' onchange='cctSMprog.ScriptSelectorChangeEditor()' style='width: 184px;'>";var middle="</select><br>Script Name: <select name='scriptname' id='scriptname' style='width: 205px;'>";var end="</select><br>Parameters for the Script: <input name='scriptparam' id='scriptparam' type='text' value='' />";var langs=cctSMprog.create_Language_List();cctSMprog.Modal_Dialog("Code Insertion",begin+langs+middle+end,"<div style='margin: auto; width: 115px;'><button class='SM_Script_button' onclick=cctSMprog.CodeInsert() style='margin: 20px 5px 5px 2px; width: 50px;'>Insert</button><button class='SM_Script_button' onclick=cctSMprog.Close_Modal_Dialog(true) style='margin: 20px 5px 5px 2px; width: 50px;'>Cancel</button></div>");cctSMprog.get_Script_List(1,function(response){jQuery('#scriptname').html(response);});});ed.addCommand('highlightCode',function(){cmd='';cctSMprog.ed=ed;var begin="Script Language: <select name='scriptlang' id='scriptlang' onchange='cctSMprog.ScriptSelectorChangeEditor()' style='width: 184px;'>";var middle="</select><br>Script Name: <select name='scriptname' id='scriptname' style='width: 205px;'>";var end="</select><br>Parameters for the Script: <input name='scriptparam' id='scriptparam' type='text' value='' />";var langs=cctSMprog.create_Language_List();cctSMprog.Modal_Dialog("Code Highlight",begin+langs+middle+end,"<div style='margin: auto; width: 115px;'><button class='SM_Script_button' onclick=cctSMprog.CodeHighlight() style='margin: 20px 5px 5px 2px; width: 50px;'>Insert</button><button class='SM_Script_button' onclick=cctSMprog.Close_Modal_Dialog(true) style='margin: 20px 5px 5px 2px; width: 50px;'>Cancel</button></div>");cctSMprog.get_Script_List(1,function(response){jQuery('#scriptname').html('<option>none</option>'+response);});});ed.addButton('smplugin',{title:'Script Manager Code Insert',image:url+'/img/inscode.png',cmd:'insertCode'});ed.addButton('smhighlight',{title:'Highlight Code',image:url+'/img/highlight.png',cmd:'highlightCode'});},createControl:function(n,cm){return null;},getInfo:function(){return({longname:'Insert/Highlight Code Plugin',author:'Richard Guay',authorurl:'http://customct.com',infourl:'http://customct.com',version:"1.0"});}});tinymce.PluginManager.add('smplugin',tinymce.plugins.smplugin);})();